// Auth request state
export const RECV_ERROR_AUTH = 'RECV_ERROR_AUTH';
export const REQ_DATA_AUTH = 'REQ_DATA_AUTH';
export const RECV_DATA_AUTH = 'RECV_DATA_AUTH';
export const RESET_AUTH = 'RESET_AUTH';

// Password Recovery request state
export const REQ_PWD_RECOVER = 'REQ_PWD_RECOVER';
export const RECV_DATA_PWD_RECOVER = 'RECV_DATA_PWD_RECOVER';
export const RECV_ERROR_PWD_RECOVER = 'RECV_ERROR_PWD_RECOVER';
export const RESET_PWD_RECOVER = 'RESET_PWD_RECOVER';

//REGISTRATION request state
export const RECV_ERROR_REGISTER = 'RECV_ERROR_REGISTER';
export const REQ_DATA_REGISTER = 'REQ_DATA_REGISTER';
export const RECV_DATA_REGISTER = 'RECV_DATA_REGISTER';
export const RESET_REGISTER = 'RESET_REGISTER';

// API request state
export const RECV_ERROR_API = 'RECV_ERROR_API';
export const REQ_DATA_API = 'REQ_DATA_API';
export const RECV_DATA_API = 'RECV_DATA_API';
export const RESET_API = 'RESET_API';

// Countries request state
export const REQ_DATA_API_COUNTRY = 'REQ_DATA_API_COUNTRY';
export const RECV_DATA_API_COUNTRY = 'RECV_DATA_API_COUNTRY';
export const RECV_ERROR_API_COUNTRY = 'RECV_ERROR_API_COUNTRY';
export const RESET_API_COUNTRY = 'RESET_API_COUNTRY';

// Real Competitors request state
export const REQ_DATA_REAL_COMPETITORS = 'REQ_DATA_REAL_COMPETITORS';
export const RECV_DATA_REAL_COMPETITORS = 'RECV_DATA_REAL_COMPETITORS';
export const RECV_ERROR_REAL_COMPETITORS = 'RECV_ERROR_REAL_COMPETITORS';
export const RESET_REAL_COMPETITORS = 'RESET_REAL_COMPETITORS';

// Players request state
export const REQ_DATA_PLAYERS = 'REQ_DATA_PLAYERS';
export const RECV_DATA_PLAYERS = 'RECV_DATA_PLAYERS';
export const RECV_ERROR_PLAYERS = 'RECV_ERROR_PLAYERS';
export const RESET_PLAYERS = 'RESET_PLAYERS';

// Virtual Competitions request state
export const REQ_DATA_VIRTUAL_COMPETITIONS = 'REQ_DATA_VIRTUAL_COMPETITIONS';
export const RECV_DATA_VIRTUAL_COMPETITIONS = 'RECV_DATA_VIRTUAL_COMPETITIONS';
export const RECV_ERROR_VIRTUAL_COMPETITIONS = 'RECV_ERROR_VIRTUAL_COMPETITIONS';
export const RESET_VIRTUAL_COMPETITIONS = 'RESET_VIRTUAL_COMPETITIONS';

// Virtual Competitor request state
export const REQ_VIRTUAL_COMPETITOR_API = 'REQ_VIRTUAL_COMPETITOR_API';
export const RECV_DATA_VIRTUAL_COMPETITOR_REGISTER = 'RECV_DATA_VIRTUAL_COMPETITOR_REGISTER';
export const RECV_DATA_VIRTUAL_COMPETITORS = "RECV_DATA_VIRTUAL_COMPETITORS";
export const RECV_ERROR_VIRTUAL_COMPETITOR_REGISTER = 'RECV_ERROR_VIRTUAL_COMPETITOR_REGISTER';
export const RECV_ERROR_VIRTUAL_COMPETITORS = "RECV_ERROR_VIRTUAL_COMPETITORS";
export const RESET_VIRTUAL_COMPETITOR_REGISTER = 'RESET_VIRTUAL_COMPETITOR_REGISTER';
export const RESET_VIRTUAL_COMPETITOR_DATA = 'RESET_VIRTUAL_COMPETITOR_DATA';

// products request state
export const REQ_PRODUCTS = 'REQ_PRODUCTS';
export const RECV_PRODUCTS_DATA = 'RECV_PRODUCTS_DATA';
export const RECV_PRODUCTS_ERROR = 'RECV_PRODUCTS_ERROR';
export const RESET_PRODUCTS = 'RESET_PRODUCTS';
